/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.EditUFPS;
import java.awt.Color;
import util.ArchivoLeerURL;
import Vista.Gui_Principal;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author docenteauditorio
 */
public class Gui_Edit extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon icono;
    int xMouse;
    int yMouse;
    /**
     * Creates new form Gui_Edit
     */

    private EditUFPS editufps;

    public Gui_Edit() {
        initComponents();
        
        setIconImage(getIconImage());
        this.setLocationRelativeTo(this);
        Gui_Principal gp = new Gui_Principal();
        gp.pintarImagen(this.logo, "src/Vista/Images/ufps.PNG");
        gp.pintarImagen(this.logo2, "src/Vista/Images/logo_ingsistemas_vertical_invertido.png");
    }
    
    //Icono
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Vista/Images/ufps_Icon.jpg"));
        return retValue;
    }

    public Gui_Edit(String url) {
        //https://gitlab.com/madarme/archivos-persistencia/-/raw/master/archivos%20texto%20plano/texto.txt

        initComponents();
        this.mostrarContenidoURL(url);

    }

    private void mostrarContenidoURL(String url) {
        ArchivoLeerURL archivo = new ArchivoLeerURL(url);
        Object datos[] = archivo.leerArchivo();
        String texto = "";
        for (Object x : datos) {
            texto = x.toString() + "\n";
        }
        this.txtDocumento.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        footer = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        txt_logo = new javax.swing.JLabel();
        txt2_logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDocumento = new javax.swing.JTextArea();
        btnGuardarListaCD = new javax.swing.JPanel();
        jLabelGuardarListaCD = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        jLabelBuscar = new javax.swing.JLabel();
        btnReemplazar = new javax.swing.JPanel();
        jLabelReemplazar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        jLabelEliminar = new javax.swing.JLabel();
        btnGuardarPDF = new javax.swing.JPanel();
        jLabelPDF = new javax.swing.JLabel();
        btnGuardarPDFSubrayado = new javax.swing.JPanel();
        jLabelPDFSubrayado = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 0, 0, 0));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        exitTxt.setText(" X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.setMaximumSize(new java.awt.Dimension(40, 40));
        exitTxt.setMinimumSize(new java.awt.Dimension(40, 40));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 1060, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        title.setFont(new java.awt.Font("Roboto Medium", 0, 62)); // NOI18N
        title.setText("EDIT UFPS");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        footer.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        footer.setText("Desarrollador: José Gabriel Fuentes - 1152085");
        jPanel1.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 652, 350, -1));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Images/ads.png"))); // NOI18N
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, 40));

        logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 100, 100));
        jPanel1.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 550, 140, 160));

        txt_logo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txt_logo.setForeground(new java.awt.Color(255, 255, 255));
        txt_logo.setText("Universidad Francisco");
        txt_logo.setToolTipText("");
        txt_logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(txt_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        txt2_logo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt2_logo.setForeground(new java.awt.Color(255, 255, 255));
        txt2_logo.setText("de Paula Santander");
        jPanel1.add(txt2_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, 30));

        txtDocumento.setEditable(false);
        txtDocumento.setColumns(20);
        txtDocumento.setRows(5);
        jScrollPane1.setViewportView(txtDocumento);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 630, 390));

        btnGuardarListaCD.setBackground(new java.awt.Color(176, 21, 14));

        jLabelGuardarListaCD.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelGuardarListaCD.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGuardarListaCD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGuardarListaCD.setText("Guardar en ListaCD");
        jLabelGuardarListaCD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGuardarListaCD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelGuardarListaCDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelGuardarListaCDMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGuardarListaCDLayout = new javax.swing.GroupLayout(btnGuardarListaCD);
        btnGuardarListaCD.setLayout(btnGuardarListaCDLayout);
        btnGuardarListaCDLayout.setHorizontalGroup(
            btnGuardarListaCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelGuardarListaCD, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnGuardarListaCDLayout.setVerticalGroup(
            btnGuardarListaCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelGuardarListaCD, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnGuardarListaCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 180, 50));

        btnBuscar.setBackground(new java.awt.Color(211, 89, 88));

        jLabelBuscar.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jLabelBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBuscar.setText("Buscar Palabra");
        jLabelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 110, 50));

        btnReemplazar.setBackground(new java.awt.Color(211, 89, 88));

        jLabelReemplazar.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jLabelReemplazar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelReemplazar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReemplazar.setText("Reemplazar");
        jLabelReemplazar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnReemplazarLayout = new javax.swing.GroupLayout(btnReemplazar);
        btnReemplazar.setLayout(btnReemplazarLayout);
        btnReemplazarLayout.setHorizontalGroup(
            btnReemplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelReemplazar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnReemplazarLayout.setVerticalGroup(
            btnReemplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelReemplazar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnReemplazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 110, 50));

        btnEliminar.setBackground(new java.awt.Color(211, 89, 88));

        jLabelEliminar.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jLabelEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEliminar.setText("Eliminar");
        jLabelEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 110, 50));

        btnGuardarPDF.setBackground(new java.awt.Color(211, 89, 88));

        jLabelPDF.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jLabelPDF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPDF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPDF.setText("Guardar PDF");
        jLabelPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnGuardarPDFLayout = new javax.swing.GroupLayout(btnGuardarPDF);
        btnGuardarPDF.setLayout(btnGuardarPDFLayout);
        btnGuardarPDFLayout.setHorizontalGroup(
            btnGuardarPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnGuardarPDFLayout.setVerticalGroup(
            btnGuardarPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPDF, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnGuardarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 110, 50));

        btnGuardarPDFSubrayado.setBackground(new java.awt.Color(211, 89, 88));

        jLabelPDFSubrayado.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jLabelPDFSubrayado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPDFSubrayado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPDFSubrayado.setText("PDF Subrayado");
        jLabelPDFSubrayado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnGuardarPDFSubrayadoLayout = new javax.swing.GroupLayout(btnGuardarPDFSubrayado);
        btnGuardarPDFSubrayado.setLayout(btnGuardarPDFSubrayadoLayout);
        btnGuardarPDFSubrayadoLayout.setHorizontalGroup(
            btnGuardarPDFSubrayadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPDFSubrayado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnGuardarPDFSubrayadoLayout.setVerticalGroup(
            btnGuardarPDFSubrayadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPDFSubrayado, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnGuardarPDFSubrayado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 110, 50));

        jLabelBackground.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Images/city2.png"))); // NOI18N
        jPanel1.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        btnExit.setBackground(new java.awt.Color(190, 0, 0));
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        btnExit.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void jLabelGuardarListaCDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGuardarListaCDMouseEntered
        this.btnGuardarListaCD.setBackground(new java.awt.Color(211,89,88));
        this.jLabelGuardarListaCD.setForeground(Color.white);
    }//GEN-LAST:event_jLabelGuardarListaCDMouseEntered

    private void jLabelGuardarListaCDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGuardarListaCDMouseExited
        this.btnGuardarListaCD.setBackground(new java.awt.Color(176,21,14));
        this.jLabelGuardarListaCD.setForeground(Color.white);
    }//GEN-LAST:event_jLabelGuardarListaCDMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnGuardarListaCD;
    private javax.swing.JPanel btnGuardarPDF;
    private javax.swing.JPanel btnGuardarPDFSubrayado;
    private javax.swing.JPanel btnReemplazar;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelEliminar;
    private javax.swing.JLabel jLabelGuardarListaCD;
    private javax.swing.JLabel jLabelPDF;
    private javax.swing.JLabel jLabelPDFSubrayado;
    private javax.swing.JLabel jLabelReemplazar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel title;
    private javax.swing.JLabel txt2_logo;
    private javax.swing.JTextArea txtDocumento;
    private javax.swing.JLabel txt_logo;
    // End of variables declaration//GEN-END:variables
}
